const char *help = "usage: cryptutil [options].\n\n"
"Available options:\n"
"-help:       \tprint this help message.\n"
"-in:         \tinput file.\n"
"-out:        \toutput file.\n"
"-encrypt:    \tperform AES encryption.\n"
"-decrypt:    \tperform AES decryption.\n"
"-encode:     \tbase64 encode the output before saving to output file.\n"
"-decode:     \tbase64 decode the input before any other operation.\n"
"-rsa_encrypt:\tperform RSA encryption.\n"
"-rsa_decrypt:\tperform RSA decryption.\n"
"-sign:       \tsign input file.\n"
"-verify:     \tperform RSA signature verification.\n"
"-signature:  \tsignature file.\n"
"-key:        \trequired RSA key for selected operation.";